CREATE TABLE Port(
	PKGORIGIN          TEXT NOT NULL,
	PORTNAME           TEXT NOT NULL,
	PORTVERSION        TEXT NOT NULL,
	DISTVERSION        TEXT NOT NULL,
	DISTVERSIONPREFIX  TEXT NULL,
	DISTVERSIONSUFFIX  TEXT NULL,
	PORTREVISION       INTEGER NULL,
	MAINTAINER         TEXT NOT NULL,
	WWW                TEXT NULL,
	FLAVORS            TEXT NULL,
	PRIMARY KEY (PKGORIGIN)
) STRICT;
CREATE TABLE PortFlavor(
	PKGORIGIN          TEXT NOT NULL,
	FLAVOR             TEXT NULL,
	COMMENT            TEXT NOT NULL,
	PKGBASE            TEXT NOT NULL,
	PKGNAME            TEXT NOT NULL,
	PRIMARY KEY (PKGORIGIN, FLAVOR),
	FOREIGN KEY (PKGORIGIN) REFERENCES Port (PKGORIGIN)
) STRICT;
CREATE TABLE Depends(
	PARENT_PKGORIGIN     TEXT NOT NULL,
	PARENT_FLAVOR        TEXT NULL,
	CHILD_PKGORIGIN      TEXT NOT NULL,
	CHILD_FLAVOR         TEXT NULL,
	KIND                 TEXT NOT NULL,
	PRIMARY KEY (PARENT_PKGORIGIN, PARENT_FLAVOR, CHILD_PKGORIGIN, CHILD_FLAVOR, KIND),
	FOREIGN KEY (PARENT_PKGORIGIN, PARENT_FLAVOR) REFERENCES PortFlavor(PKGORIGIN, FLAVOR),
	FOREIGN KEY (CHILD_PKGORIGIN, CHILD_FLAVOR) REFERENCES PortFlavor(PKGORIGIN, FLAVOR)
) STRICT;

CREATE INDEX Port_Portname ON Port(PORTNAME);
CREATE INDEX Port_Maintaner ON Port(MAINTAINER);
CREATE INDEX Depends_ByChild ON Depends(CHILD_PKGORIGIN, CHILD_FLAVOR);
