SELECT
	CASE
		WHEN P.PKGORIGIN LIKE '%%'||PF.PKGNAMESUFFIX THEN substr(PF.PKGORIGIN, 0, length(PF.PKGORIGIN) - length(PF.PKGNAMESUFFIX) + 1)
		ELSE PF.PKGORIGIN
	END as PO
FROM
	Port P,
	PortFlavor PF
WHERE
	PF.PKGORIGIN = P.PKGORIGIN
GROUP BY
	PO
